### ISSUE TITLE
HTTP Error 404: Not Found for URL https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl

### ISSUE THREAD

**Issue by Nayana-ibm** [ScatterHQ/flocker#13]
I am facing below issue while building flocker: 

` pip install https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl`

```
Downloading/unpacking https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl
  HTTP error 404 while getting https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl
  Could not install requirement https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl because of error HTTP Error 404: Not Found
Cleaning up...
Could not install requirement https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl because of HTTP error HTTP Error 404: Not Found for URL https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl
Storing complete log in /home/nayana/.pip/pip.log
(flocker-client)[nayana@ecos0011 flocker_rhel_setup]$ pip install https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl
Downloading/unpacking https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl
  HTTP error 404 while getting https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl
  Could not install requirement https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl because of error HTTP Error 404: Not Found
Cleaning up...
Could not install requirement https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl because of HTTP error HTTP Error 404: Not Found for URL https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl

```

Reference: https://flocker.readthedocs.io/en/latest/docker-integration/install-client.html
Distribution: RHEL

**Comment by itamarst** [comment]
As a workaround I believe you can do

```
pip install git+git://github.com/ScatterHQ/flocker.git@1.15.0
```

**Comment by Nayana-ibm** [comment]
@itamarst Thanks for your inputs. I tried the mentioned command however facing below issue: 
```
$ pip install git+git://github.com/ScatterHQ/flocker.git@1.15.0
Downloading/unpacking git+git://github.com/ScatterHQ/flocker.git@1.15.0
  Cloning git://github.com/ScatterHQ/flocker.git (to 1.15.0) to /tmp/pip-sOpPzd-build
  Running setup.py egg_info for package from git+git://github.com/ScatterHQ/flocker.git@1.15.0
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-sOpPzd-build/setup.py", line 8, in <module>
        from pkg_resources import parse_requirements, RequirementParseError
    ImportError: cannot import name RequirementParseError
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-sOpPzd-build/setup.py", line 8, in <module>

    from pkg_resources import parse_requirements, RequirementParseError

ImportError: cannot import name RequirementParseError

```

Steps:

- sudo yum install -y gcc git libffi-devel openssl-devel python python-devel python-virtualenv
-  virtualenv --python=/usr/bin/python2.7 flocker-client
- source flocker-client/bin/activate pip install --upgrade pip
-  pip install https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.15.0-py2-none-any.whl

 Now, tried with 
   pip install git+git://github.com/ScatterHQ/flocker.git@1.15.0 

version:  Python 2.7.5
Ref:  https://flocker.readthedocs.io/en/latest/docker-integration/install-client.html

**Comment by itamarst** [comment]
```console
[itamarst@blake ~]$ virtualenv /tmp/test
New python executable in /tmp/test/bin/python2
Also creating executable in /tmp/test/bin/python
Installing setuptools, pip, wheel...done.
[itamarst@blake ~]$ source /tmp/test/bin/activate
(test) [itamarst@blake ~]$ pip install --upgrade pip
Requirement already up-to-date: pip in /tmp/test/lib/python2.7/site-packages
(test) [itamarst@blake ~]$ pip --version
pip 9.0.1 from /tmp/test/lib/python2.7/site-packages (python 2.7)
(test) [itamarst@blake ~]$ pip install git+git://github.com/ScatterHQ/flocker.git@1.15.0
...
<eventually finishes successfully>
```

What version of pip are you using? Possibly one that's too old, somehow.

**Comment by Nayana-ibm** [comment]
Using version 9.0.1 for pip

```
pip --version
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)

```

I have also tried the steps to build flocker from source.
```
yum install -y gcc-c++ git libffi-devel openssl-devel python python-devel python-virtualenv
git clone https://github.com/ClusterHQ/flocker
cd flocker
git checkout 1.15.0
sudo pip install -e .
```

Is there any dependency am missing here?

**Comment by Nayana-ibm** [comment]
Hi,

I could build flocker using below steps:
```
sudo yum install -y  gcc-c++ git libffi-devel openssl-devel python python-devel
git clone https://github.com/ClusterHQ/flocker
cd flocker
git checkout 1.15.0
pip install --requirement requirements/all.txt
pip install -e .
```
